source "https://rubygems.org"

gem 'ruboty'
gem 'ruboty-slack'
gem 'ruboty-cron'
gem 'ruboty-alias'
gem 'ruboty-github'
gem 'ruboty-google_image'
gem 'ruboty-redis'
gem 'ruboty-echo'
gem 'ruboty-japan_weather'
